language: cpp
sudo: false
cache:
  directories:
  - container
env:
- CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" DEPLOY="1"
- CMAKE_GENERATOR="Ninja" CMAKE_VERSION="latest"
- CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="3.0"
- CMAKE_GENERATOR="Ninja" CMAKE_VERSION="3.0"
- CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" COVERAGE="--use-cmake-coverage"
install:
- eval $(curl -LSs --retry 100 --connect-timeout 3 public-travis-scripts.polysquare.org/bootstrap.py | python /dev/stdin -d container -s setup/bii/setup.py -e bash -p /dev/stdout --cmake-version ${CMAKE_VERSION})
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]] ; then wget http://launchpadlibrarian.net/162564634/iwyu_3.3-4_amd64.deb; container/_languages/python/3.4.1/bin/psq-travis-container-exec container/_languages/os/Ubuntu.precise.None --distro "Ubuntu" --release "precise" --show-output -- dpkg -i --force-depends iwyu_3.3-4_amd64.deb; fi
script:
- polysquare_run check/bii/check.py ${COVERAGE} --cmake-namespace "iwyu" --generator "${CMAKE_GENERATOR}" --block "smspillaz/iwyu-target-cmake"
before_cache:
- polysquare_cleanup
after_success:
- polysquare_run coverage/bii/coverage.py
before_deploy:
- polysquare_run deploy/bii/deploy.py
deploy:
  provider: biicode
  skip_cleanup: true
  user:
    secure: Qmev4jnZQ/h+yR5MwFCaCHO2tGe9+ah8k55hva7vfUbAcGDdwVPB3dq+NdwmQcLs/YXI1HKTw9uBvY/5uKQXB92B+r0blaBJCvGeNrFlJCV7eJ8zjD5ublcaOAvLNJmNCk7tO2gTGW+tOO+9XGrYSSoDh0v5mUpkPmIkxs4bQnE=
  password:
    secure: BrVk9kQ/VyWlCtGU0FFXELv7kqVHWYblcoQ6tbFBvakKNLyi1Ea1L/+MM/mYbLKd8+JWzHsB5b98C2ve2740P6I8M7SfuaVnL9f0HckIL4Y8c4nD1QMbGDUlqxhb1k63rjNovKcOPSA4w19moD50AYyXHQSllECEgLn99NXNqS8=
  on:
    repo: polysquare/iwyu-target-cmake
    branch: master
    condition: ${DEPLOY} = 1
